CREATE TABLE USUARIO (
    INT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    CPF VARCHAR(11), 
    LOGRADOURO VARCHAR(100),
    ESTADO VARCHAR(50),
    NUMERO VARCHAR(10),
    NASCIMENTO DATE,
    PERFIL INT,
    CIDADE VARCHAR(100),
    BAIRRO VARCHAR(50)
);

CREATE TABLE PROTOCOLO (
    HORARIO INT PRIMARY KEY,
    DATA DATE,
    ASSUNTO VARCHAR(150)
);

CREATE TABLE USUARIO_PROTOCOLO (
    USUARIO_ID INT,
    PROTOCOLO_HORARIO INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(INT_ID),
    FOREIGN KEY (PROTOCOLO_HORARIO) REFERENCES PROTOCOLO(HORARIO)
);
